### ISSUE TITLE
Pointnet2 missing

### ISSUE THREAD

**Issue by liuxuexun** [heshuting555/RefMask3D#1]
Hi, thanks for opening your great work.

I set up the env following your README, and I can't find the pointnet2 folder when I run `cd ../../pointnet2`.

I wonder know how to fix it, thank you.

**Comment by heshuting555** [comment]
Thank you for your interest in our work!

Sorry for forgetting to upload the file. This file is the same as the one in [Mask3D](https://github.com/JonasSchult/Mask3D).

**Comment by liuxuexun** [comment]
Thank you, the problem has been solved.
